Repository opencast/pyCA, pull requests merged in 2020-06, with the labels that each got.

#176 Start a new UI reload
  .gitignore
  .travis.yml
  MANIFEST.in
  Makefile
  package-lock.json
  package.json
  pyca/ui/__init__.py
  pyca/ui/jsonapi.py
  pyca/ui/static/func.js
  pyca/ui/static/jquery.min.js
  pyca/ui/templates/home.html
  pyca/ui/templates/layout.html
  pyca/ui/utils.py
  readme.rst
  start.sh
  tests/test_restapi.py
  tests/test_ui.py
  ui/func.js
  ui/index.html
  ui/server.js
  ui/style.css
Labels: enhancement

#178 Fix Configuration Load Order
  pyca/__main__.py
Labels: bug, documentation

#201 Fix Response Encoding
  pyca/utils.py
Labels: bug

#203 Make safe_start_capture actually safe
  pyca/capture.py
Labels: bug
